# Generated by Django 6.0.1 on 2026-01-15 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_intensity', models.IntegerField()),
                ('pad_change_frequency', models.IntegerField()),
                ('flooding', models.IntegerField()),
                ('clot_size', models.IntegerField()),
                ('period_duration', models.IntegerField()),
                ('flow_pattern', models.IntegerField()),
                ('spotting_between', models.IntegerField()),
                ('cycle_regular', models.IntegerField()),
                ('avg_cycle_group', models.IntegerField()),
                ('pain_level', models.IntegerField()),
                ('pain_interference', models.IntegerField()),
                ('fatigue', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('headaches', models.BooleanField(default=False)),
                ('mood_changes', models.IntegerField()),
                ('mood_impact', models.IntegerField()),
                ('pcos', models.BooleanField(default=False)),
                ('endometriosis', models.BooleanField(default=False)),
                ('thyroid', models.BooleanField(default=False)),
                ('anemia_history', models.IntegerField()),
                ('wants_health_alerts', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
