# Generated by Django 5.2 on 2026-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='brain_fog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='exercise_frequency',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='missed_periods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pain_location',
            field=models.CharField(default='lower_abdomen', max_length=20),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pain_type',
            field=models.CharField(default='cramping', max_length=20),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_acne_breakouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_bloating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_breast_tenderness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_depression_anxiety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_irritability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_joint_muscle_pain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='pms_mood_swings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='sleep_quality',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='stress_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='uterine_fibroids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualhealthprofile',
            name='weight_changes',
            field=models.CharField(default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='menstrualhealthprofile',
            name='anemia_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menstrualhealthprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
